import { sql } from "kysely";
import { afterAll, beforeAll, describe, expect, it } from "vite-plus/test";
import type { SchemaMeta } from "@yuiitsu/core";
import { createAutoApi } from "@yuiitsu/core";
import { call, makeApp } from "./support/app";
import { DIALECTS, makeTarget, type DialectName, type Target } from "./support/targets";

const EXTRA: Record<DialectName, string[]> = {
  postgres: [
    `create table cpk (a integer, b integer, primary key (a, b))`,
    `create table uuid_pk (id uuid primary key default gen_random_uuid(), name text)`,
  ],
  mysql: [
    `create table cpk (a int, b int, primary key (a, b)) engine=InnoDB`,
    `create table uuid_pk (id varchar(36) not null default (uuid()) primary key, name varchar(32)) engine=InnoDB`,
    `create table myisam_t (id int primary key, v int) engine=MyISAM`,
    `create table latin1_t (id int primary key, name varchar(10) character set latin1) engine=InnoDB`,
  ],
  sqlite: [
    `create table cpk (a integer, b integer, primary key (a, b))`,
    `create table uuid_pk (id text primary key default (lower(hex(randomblob(16)))), name text)`,
    `create table gen_t (id integer primary key, a integer not null, b integer generated always as (a * 2) stored, c integer as (a + 1))`,
    `create table wr_t (k text primary key, v integer) without rowid`,
    `create table not_alias (id int primary key, v integer)`,
  ],
};

describe.each(DIALECTS)("startup validation (%s)", (name) => {
  let t: Target;
  let schema: SchemaMeta;
  beforeAll(async () => {
    t = await makeTarget(name, EXTRA[name]);
    schema = await t.dialect.introspect(t.db, { pgSchema: t.pgSchema });
  });
  afterAll(async () => {
    await t.teardown();
  });

  const fails = (tables: any, pattern: RegExp, extra: any = {}) =>
    expect(makeApp(t, tables, extra)).rejects.toThrow(pattern);

  it("rejects unknown tables (names are case-sensitive)", async () => {
    await fails({ nope: { operations: ["read"] } }, /not found/);
    await fails({ ORDERS: { operations: ["read"] } }, /not found/);
  });

  it("rejects empty or unknown operations", async () => {
    await fails({ orders: { operations: [] } }, /operations must not be empty/);
    await fails({ orders: { operations: ["purge"] } }, /unknown operation/);
  });

  it("rejects composite keys and write operations on tables without a primary key", async () => {
    await fails({ cpk: { operations: ["read"] } }, /composite primary keys/);
    await fails({ tags: { operations: ["read", "create"] } }, /without a primary key/);
    expect(await makeApp(t, { tags: { operations: ["read"] } })).toBeDefined();
  });

  it("validates columns lists", async () => {
    await fails(
      { orders: { operations: ["read"], columns: { read: ["nope"] } } },
      /unknown column/,
    );
    await fails(
      { orders: { operations: ["create"], columns: { create: ["id"] } } },
      /generated by the database/,
    );
    await fails(
      { orders: { operations: ["update"], columns: { update: ["id"] } } },
      /generated by the database|primary key/,
    );
    await fails(
      { stock: { operations: ["update"], columns: { update: ["sku", "id"] } } },
      /primary key|generated/,
    );
  });

  it("validates limits", async () => {
    await fails({ orders: { operations: ["read"] } }, /defaultLimit/, {
      limits: { defaultLimit: 100, maxLimit: 10 },
    });
    await fails({ orders: { operations: ["read"] } }, /positive integer/, {
      limits: { maxInValues: 0 },
    });
  });

  it("rejects a schema generated for another dialect", async () => {
    await fails({ orders: { operations: ["read"] } }, /generated for/, {
      schema: { ...schema, dialect: name === "sqlite" ? "mysql" : "sqlite" },
    });
  });

  it("rejects table names that cannot be used in a path", async () => {
    const weird: SchemaMeta = { ...schema, tables: [{ ...schema.tables[0]!, name: "a-b" }] };
    await fails({ "a-b": { operations: ["read"] } }, /API path/, { schema: weird });
  });

  it("rejects delete when the dialect has neither RETURNING nor locking reads", async () => {
    const crippled = {
      ...t.dialect,
      capabilities: { ...t.dialect.capabilities, returning: false, lockingRead: false },
    };
    await fails({ orders: { operations: ["delete"] } }, /delete is not supported/, {
      dialect: crippled,
    });
  });

  it("warns about reserved parameter names and hides them from the filter parameters", async () => {
    const mutated: SchemaMeta = JSON.parse(JSON.stringify(schema));
    const orders = mutated.tables.find((x) => x.name === "orders")!;
    orders.columns.push({ ...orders.columns.find((c) => c.name === "note")!, name: "offset" });
    const messages: string[] = [];
    const app = await makeApp(
      t,
      { orders: { operations: ["read"] } },
      { schema: mutated, onWarning: (m: string) => messages.push(m) },
    );
    expect(messages.some((m) => /reserved/.test(m) && m.includes("offset"))).toBe(true);
    const doc: any = await (async () => {
      app.doc31("/o", { openapi: "3.1.0", info: { title: "t", version: "1" } });
      return (await app.request("/o")).json();
    })();
    const params = doc.paths["/api/orders"].get.parameters.filter((p: any) => p.name === "offset");
    expect(params).toHaveLength(1);
    expect(params[0].schema.type).toBe("integer");
  });

  it.skipIf(name !== "postgres")("only sees the configured pgSchema", async () => {
    await expect(
      createAutoApi({ db: t.db, dialect: t.dialect, tables: { orders: { operations: ["read"] } } }),
    ).rejects.toThrow(/not found/); // 既定の public には orders がない
  });

  describe("warnings", () => {
    it.skipIf(name !== "mysql")("warns when the MySQL session time zone is not UTC", async () => {
      const one = await t.open({ poolSize: 1 });
      await sql`set time_zone = '+09:00'`.execute(one);
      const messages: string[] = [];
      await makeApp(
        { ...t, db: one } as Target,
        { orders: { operations: ["read"] } },
        { onWarning: (m: string) => messages.push(m) },
      );
      expect(messages.some((m) => /time_zone/.test(m))).toBe(true);
      await one.destroy();
    });

    it.skipIf(name !== "sqlite")("warns when foreign_keys is OFF", async () => {
      await sql`pragma foreign_keys = off`.execute(t.db);
      const messages: string[] = [];
      await makeApp(
        t,
        { orders: { operations: ["read"] } },
        { onWarning: (m: string) => messages.push(m) },
      );
      expect(messages.some((m) => /foreign_keys/.test(m))).toBe(true);
      await sql`pragma foreign_keys = on`.execute(t.db);
    });

    it.skipIf(name === "postgres")(
      "warns when the primary key may not be identifiable after INSERT without RETURNING",
      async () => {
        const messages: string[] = [];
        await makeApp(
          t,
          { uuid_pk: { operations: ["create"] } },
          { onWarning: (m: string) => messages.push(m) },
        );
        // RETURNING 対応の方言では不要。MySQL のみ警告する
        expect(messages.some((m) => /primary key may not be identifiable/.test(m))).toBe(
          name === "mysql",
        );
      },
    );
  });

  describe.skipIf(name !== "mysql")("MySQL specifics", () => {
    it("rejects non-InnoDB tables and lower_case_table_names mismatches", async () => {
      await fails({ myisam_t: { operations: ["read"] } }, /InnoDB/);
      await fails({ MyIsam_T: { operations: ["read"] } }, /not found/);
    });

    it("fails (500) and rolls back when the primary key cannot be identified after INSERT", async () => {
      const app = await makeApp(t, { uuid_pk: { operations: ["read", "create"] } });
      const r = await call(app, "POST", "/uuid_pk", { body: { name: "x" } });
      expect(r.status).toBe(500);
      expect(
        Number(
          (
            (await sql<{ n: unknown }>`select count(*) as n from uuid_pk`.execute(t.db))
              .rows[0] as any
          ).n,
        ),
      ).toBe(0);
      const ok = await call(app, "POST", "/uuid_pk", {
        body: { id: "11111111-1111-1111-1111-111111111111", name: "x" },
      });
      expect(ok.status, ok.text).toBe(201);
    });

    it("does not provide like/ilike for non-utf8mb4 columns", async () => {
      const app = await makeApp(t, { latin1_t: { operations: ["read"] } });
      expect((await call(app, "GET", "/latin1_t?name=like.a%25")).status).toBe(400);
      expect((await call(app, "GET", "/latin1_t?name=eq.a")).status).toBe(200);
    });

    it("eq follows the column collation (case-insensitive by default), like does not", async () => {
      await t.db.insertInto("orders").values({ user_id: "Alice", total: 1 }).execute();
      const app = await makeApp(t, { orders: { operations: ["read"] } });
      expect((await call(app, "GET", "/orders?user_id=eq.alice")).json).toHaveLength(1); // 方言差: 他の方言は 0 件
      expect((await call(app, "GET", "/orders?user_id=like.alice")).json).toHaveLength(0);
      expect((await call(app, "GET", "/orders?user_id=ilike.alice")).json).toHaveLength(1);
      await sql`delete from orders`.execute(t.db);
    });
  });

  describe.skipIf(name === "mysql")("case sensitivity of eq", () => {
    it("eq is case-sensitive", async () => {
      await t.db.insertInto("orders").values({ user_id: "Alice", total: 1 }).execute();
      const app = await makeApp(t, { orders: { operations: ["read"] } });
      expect((await call(app, "GET", "/orders?user_id=eq.alice")).json).toHaveLength(0);
      expect((await call(app, "GET", "/orders?user_id=eq.Alice")).json).toHaveLength(1);
      await sql`delete from orders`.execute(t.db);
    });
  });

  describe.skipIf(name !== "sqlite")("SQLite specifics", () => {
    it("detects rowid aliases, generated columns and WITHOUT ROWID tables", () => {
      const col = (tb: string, c: string) =>
        schema.tables.find((x) => x.name === tb)!.columns.find((x) => x.name === c)!;
      expect(col("gen_t", "id")).toMatchObject({ isAutoIncrement: true, isGenerated: true });
      expect(col("gen_t", "b")).toMatchObject({ isGenerated: true, isAutoIncrement: false });
      expect(col("gen_t", "c")).toMatchObject({ isGenerated: true });
      expect(col("wr_t", "k")).toMatchObject({ isAutoIncrement: false });
      expect(col("not_alias", "id")).toMatchObject({ isAutoIncrement: false, isGenerated: false });
    });

    it("does not allow writing generated columns by default", async () => {
      const app = await makeApp(t, { gen_t: { operations: ["read", "create"] } });
      expect((await call(app, "POST", "/gen_t", { body: { a: 2, b: 9 } })).status).toBe(400);
      const ok = await call(app, "POST", "/gen_t", { body: { a: 2 } });
      expect(ok.status, ok.text).toBe(201);
      expect(ok.json).toMatchObject({ a: 2, b: 4, c: 3 });
    });
  });
});
