import { OpenAPIHono } from "@hono/zod-openapi";
import { jwt } from "hono/jwt";
import type { Kysely } from "kysely";
import { createAutoApi, type DialectAdapter } from "@yuiitsu/core";
import { sqliteDialect } from "@yuiitsu/dialect-sqlite";
import type { Generated } from "kysely";

/** kysely-codegen で生成する型の代わり */
export interface DB {
  orders: {
    id: Generated<number>;
    user_id: string;
    status: Generated<string>;
    total: number;
    internal_note: string | null;
  };
  inventory: { id: Generated<number>; sku: string; stock: number };
}

export type AppEnv = { Variables: { jwtPayload: { sub: string } } };

export const DDL = [
  `create table orders (
     id integer primary key autoincrement,
     user_id text not null,
     status text not null default 'new',
     total integer not null check (total > 0),
     internal_note text
   )`,
  `create table inventory (id integer primary key autoincrement, sku text not null unique, stock integer not null check (stock >= 0))`,
];

/** 手動確認用(server.ts)の PostgreSQL / MySQL 向け DDL。SQLite は上の DDL */
export const DDL_POSTGRES = [
  `create table orders (
     id bigint generated by default as identity primary key,
     user_id text not null,
     status text not null default 'new',
     total integer not null check (total > 0),
     internal_note text
   )`,
  `create table inventory (id bigint generated by default as identity primary key, sku varchar(64) not null unique, stock integer not null check (stock >= 0))`,
];

export const DDL_MYSQL = [
  `create table orders (
     id bigint auto_increment primary key,
     user_id varchar(64) not null,
     status varchar(32) not null default 'new',
     total int not null check (total > 0),
     internal_note text
   ) engine=InnoDB`,
  `create table inventory (id bigint auto_increment primary key, sku varchar(64) not null unique, stock int not null check (stock >= 0)) engine=InnoDB`,
];

export async function buildApp(
  db: Kysely<DB>,
  jwtSecret: string,
  dialect: DialectAdapter = sqliteDialect(),
  opts: { pgSchema?: string } = {},
) {
  const app = new OpenAPIHono<AppEnv>();

  // 認証は利用者の責務。マウントより前に登録する
  app.use("/api/*", jwt({ secret: jwtSecret, alg: "HS256" }));

  const api = await createAutoApi<DB, AppEnv>({
    db,
    dialect,
    pgSchema: opts.pgSchema,
    tables: {
      orders: {
        operations: ["read", "create", "update"],
        columns: {
          read: ["id", "status", "total"],
          create: ["total"],
          update: ["status"],
        },
        // 行の絞り込み: ログインユーザーの注文だけ
        scope: (c) => ({ user_id: { eq: c.get("jwtPayload").sub } }),
        hooks: {
          // 所有者はサーバー側で設定する(クライアントには要求しない)
          beforeCreate: async (ctx, data) => ({ ...data, user_id: ctx.c.get("jwtPayload").sub }),
          // テーブルを跨ぐ処理: 注文の作成と同じトランザクションで在庫を減らす
          afterCreate: async (ctx) => {
            await ctx.db
              .updateTable("inventory")
              .set((eb) => ({ stock: eb("stock", "-", 1) }))
              .where("sku", "=", "WIDGET")
              .execute();
          },
          // コミット後の処理(配送保証なし)
          afterCommitCreate: async (_ctx, row) => {
            console.info(`order ${row.id} created`);
          },
        },
      },
      inventory: { operations: ["read"] },
    },
  });
  app.route("/api", api);

  // ドキュメントの配信も利用者の責務
  app.openAPIRegistry.registerComponent("securitySchemes", "bearerAuth", {
    type: "http",
    scheme: "bearer",
    bearerFormat: "JWT",
  });
  app.doc31("/openapi.json", {
    openapi: "3.1.0",
    info: { title: "Example API", version: "1.0.0" },
    security: [{ bearerAuth: [] }],
  });
  // 手動確認用の Swagger UI(CDN から読み込む。ライブラリの機能ではない)
  app.get("/docs", (c) =>
    c.html(`<!doctype html>
<html><head><meta charset="utf-8"><title>Example API</title>
<link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css"></head>
<body><div id="ui"></div>
<script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
<script>SwaggerUIBundle({ url: "/openapi.json", dom_id: "#ui" });</script>
</body></html>`),
  );
  return app;
}
