import { OPERATIONS, resolveColumns } from "./columns";
import { RESERVED_PARAMS } from "./query";
import { pascalCase } from "./schemas";
import type {
  AutoApiOptions,
  ColumnMeta,
  DialectAdapter,
  Operation,
  SchemaMeta,
  TableConfig,
  TableMeta,
} from "./types";

export type TableRuntime = {
  name: string;
  meta: TableMeta;
  byName: Map<string, ColumnMeta>;
  ops: Set<Operation>;
  readCols: ColumnMeta[];
  readMap: Map<string, ColumnMeta>;
  createCols: ColumnMeta[];
  updateCols: ColumnMeta[];
  pk: ColumnMeta | null;
  config: TableConfig<any, any, any>;
};

export type ResolvedLimits = { defaultLimit: number; maxLimit: number; maxInValues: number };

export function resolveLimits(limits: AutoApiOptions["limits"]): ResolvedLimits {
  const r = {
    defaultLimit: limits?.defaultLimit ?? 50,
    maxLimit: limits?.maxLimit ?? 1000,
    maxInValues: limits?.maxInValues ?? 100,
  };
  for (const [k, v] of Object.entries(r)) {
    if (!Number.isInteger(v) || v < 1) throw new Error(`limits.${k} must be a positive integer`);
  }
  if (r.defaultLimit > r.maxLimit)
    throw new Error("limits.defaultLimit must be <= limits.maxLimit");
  return r;
}

const NAME_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

/** 起動時の検証(fail fast)と、警告の収集 */
export function buildRuntimes(
  options: AutoApiOptions<any, any>,
  schema: SchemaMeta,
  dialect: DialectAdapter,
): { runtimes: TableRuntime[]; warnings: string[] } {
  const warnings: string[] = [];
  const runtimes: TableRuntime[] = [];
  const componentNames = new Map<string, string>();
  const reserved = new Set<string>(RESERVED_PARAMS);

  for (const [name, rawConfig] of Object.entries(
    options.tables as Record<string, TableConfig<any, any, any> | undefined>,
  )) {
    if (!rawConfig) continue;
    const config = rawConfig;
    const where = `tables.${name}`;
    if (!NAME_RE.test(name)) throw new Error(`${where}: table name cannot be used in an API path`);
    const meta = schema.tables.find((t) => t.name === name);
    if (!meta)
      throw new Error(`${where}: table not found in the schema (names are case-sensitive)`);
    dialect.assertTableSupported(meta);

    if (!Array.isArray(config.operations) || config.operations.length === 0) {
      throw new Error(`${where}: operations must not be empty`);
    }
    for (const op of config.operations) {
      if (!OPERATIONS.includes(op)) throw new Error(`${where}: unknown operation "${op}"`);
    }
    const ops = new Set<Operation>(config.operations);

    if (meta.primaryKey.length > 1)
      throw new Error(`${where}: composite primary keys are not supported`);
    const pkName = meta.primaryKey[0];
    if (!pkName && [...ops].some((o) => o !== "read")) {
      throw new Error(`${where}: tables without a primary key only support the "read" operation`);
    }
    if (ops.has("delete") && !dialect.capabilities.returning && !dialect.capabilities.lockingRead) {
      throw new Error(`${where}: delete is not supported by the ${dialect.name} dialect`);
    }

    const byName = new Map(meta.columns.map((c) => [c.name, c]));
    const cols = config.columns;
    for (const kind of ["read", "create", "update"] as const) {
      for (const cn of cols?.[kind] ?? []) {
        const c = byName.get(cn);
        if (!c) throw new Error(`${where}.columns.${kind}: unknown column "${cn}"`);
        if (kind !== "read") {
          if (c.type === "unknown")
            throw new Error(
              `${where}.columns.${kind}: column "${cn}" has an unsupported type and is read-only`,
            );
          if (c.isGenerated || c.isAutoIncrement)
            throw new Error(
              `${where}.columns.${kind}: column "${cn}" is generated by the database`,
            );
        }
        if (kind === "update" && cn === pkName)
          throw new Error(`${where}.columns.update: the primary key cannot be updated`);
      }
    }
    const pick = (names: string[]) => names.map((n) => byName.get(n)!);
    const readCols = pick(resolveColumns(meta, cols, "read"));
    const createCols = pick(resolveColumns(meta, cols, "create"));
    const updateCols = pick(resolveColumns(meta, cols, "update"));

    const comp = pascalCase(name);
    const prior = componentNames.get(comp);
    if (prior)
      throw new Error(`${where}: OpenAPI component name "${comp}" collides with table "${prior}"`);
    componentNames.set(comp, name);

    for (const c of readCols) {
      if (reserved.has(c.name)) {
        warnings.push(
          `${where}: column "${c.name}" has a reserved query parameter name and cannot be filtered`,
        );
      }
    }
    const pk = pkName ? byName.get(pkName)! : null;
    if (
      pk &&
      ops.has("create") &&
      !dialect.capabilities.returning &&
      !pk.isAutoIncrement &&
      (pk.hasDefault || pk.isGenerated)
    ) {
      warnings.push(
        `${where}: the primary key may not be identifiable after INSERT on ${dialect.name}; create can fail with 500 unless the primary key is supplied`,
      );
    }

    runtimes.push({
      name,
      meta,
      byName,
      ops,
      readCols,
      readMap: new Map(readCols.map((c) => [c.name, c])),
      createCols,
      updateCols,
      pk,
      config,
    });
  }
  return { runtimes, warnings };
}
