import Database from "better-sqlite3";
import { Kysely, MysqlDialect, PostgresDialect, SqliteDialect, sql } from "kysely";
import { createPool } from "mysql2";
import mysql from "mysql2/promise";
import pg from "pg";
import { mysqlDialect } from "@yuiitsu/dialect-mysql";
import { postgresDialect } from "@yuiitsu/dialect-postgres";
import { sqliteDialect } from "@yuiitsu/dialect-sqlite";
import type { DialectAdapter } from "@yuiitsu/core";
import { mysqlConfig, pgConfig, workerId } from "./env";

export type DialectName = "postgres" | "mysql" | "sqlite";
export const DIALECTS: DialectName[] = ["postgres", "mysql", "sqlite"];

export type Target = {
  name: DialectName;
  dialect: DialectAdapter;
  db: Kysely<any>;
  pgSchema?: string;
  /** 他の接続を作る(プール 1 など) */
  open(opts?: { poolSize?: number; acquireTimeoutMs?: number }): Promise<Kysely<any>>;
  exec(statements: string[]): Promise<void>;
  tables: string[];
  reset(): Promise<void>;
  teardown(): Promise<void>;
};

/** 全方言で同じ NormalizedType になる型だけを使った共通スキーマ(uuid は使わない) */
const DDL: Record<DialectName, string[]> = {
  postgres: [
    `create table orders (
      id bigint generated by default as identity primary key,
      user_id text not null,
      status text not null default 'new',
      total integer not null,
      note text,
      secret text,
      paid boolean not null default false,
      meta jsonb,
      score double precision,
      created_at timestamptz(3) not null default now()
    )`,
    `create table stock (id bigint generated by default as identity primary key, sku varchar(64) not null unique, qty integer not null)`,
    `create table audit_log (id bigint generated by default as identity primary key, message text not null, ref_id bigint)`,
    `create table tags (label text not null, n integer)`,
    `create table fk_parent (id integer primary key)`,
    `create table fk_child (id bigint generated by default as identity primary key, parent_id integer not null references fk_parent (id))`,
    `create table check_t (id bigint generated by default as identity primary key, n integer not null check (n > 0))`,
  ],
  mysql: [
    `create table orders (
      id bigint auto_increment primary key,
      user_id varchar(64) not null,
      status varchar(32) not null default 'new',
      total int not null,
      note text,
      secret text,
      paid boolean not null default false,
      meta json,
      score double,
      created_at timestamp(3) not null default current_timestamp(3)
    ) engine=InnoDB`,
    `create table stock (id bigint auto_increment primary key, sku varchar(64) not null unique, qty int not null) engine=InnoDB`,
    `create table audit_log (id bigint auto_increment primary key, message text not null, ref_id bigint) engine=InnoDB`,
    `create table tags (label varchar(64) not null, n int) engine=InnoDB`,
    `create table fk_parent (id int primary key) engine=InnoDB`,
    `create table fk_child (id bigint auto_increment primary key, parent_id int not null, foreign key (parent_id) references fk_parent (id)) engine=InnoDB`,
    `create table check_t (id bigint auto_increment primary key, n int not null, check (n > 0)) engine=InnoDB`,
  ],
  sqlite: [
    `create table orders (
      id integer primary key autoincrement,
      user_id text not null,
      status text not null default 'new',
      total integer not null,
      note text,
      secret text,
      paid boolean not null default 0 check (paid in (0, 1)),
      meta json,
      score real,
      created_at datetime not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
    )`,
    `create table stock (id integer primary key autoincrement, sku text not null unique, qty integer not null)`,
    `create table audit_log (id integer primary key autoincrement, message text not null, ref_id integer)`,
    `create table tags (label text not null, n integer)`,
    `create table fk_parent (id integer primary key)`,
    `create table fk_child (id integer primary key autoincrement, parent_id integer not null references fk_parent (id))`,
    `create table check_t (id integer primary key autoincrement, n integer not null check (n > 0))`,
  ],
};

const TABLES = ["orders", "stock", "audit_log", "tags", "fk_parent", "fk_child", "check_t"];
const FK_TABLES = ["fk_child", "fk_parent"];

async function runAll(db: Kysely<any>, statements: string[]) {
  for (const s of statements) await sql.raw(s).execute(db);
}

export async function makeTarget(name: DialectName, extraDdl: string[] = []): Promise<Target> {
  const w = workerId();
  if (name === "postgres") {
    const schema = `test_w${w}`;
    const admin = new pg.Client(pgConfig());
    await admin.connect();
    await admin.query(`drop schema if exists ${schema} cascade`);
    await admin.query(`create schema ${schema}`);
    await admin.end();
    const open = async (opts: { poolSize?: number; acquireTimeoutMs?: number } = {}) =>
      new Kysely<any>({
        dialect: new PostgresDialect({
          pool: new pg.Pool({
            ...pgConfig(),
            max: opts.poolSize ?? 5,
            connectionTimeoutMillis: opts.acquireTimeoutMs ?? 10_000,
            options: `-c search_path=${schema}`,
          }),
        }),
      });
    const db = await open();
    await runAll(db, [...DDL.postgres, ...extraDdl]);
    return {
      name,
      dialect: postgresDialect(),
      db,
      pgSchema: schema,
      open,
      exec: (s) => runAll(db, s),
      tables: TABLES,
      reset: async () => {
        await sql.raw(`truncate table ${TABLES.join(", ")} restart identity`).execute(db);
      },
      teardown: async () => {
        await db.destroy();
      },
    };
  }

  if (name === "mysql") {
    const database = `autoapi_test_w${w}`;
    const cfg = mysqlConfig();
    const admin = await mysql.createConnection({ ...cfg, database: undefined });
    await admin.query(`drop database if exists \`${database}\``);
    await admin.query(`create database \`${database}\``);
    await admin.end();
    const open = async (opts: { poolSize?: number } = {}) => {
      const pool = createPool({
        ...cfg,
        database,
        connectionLimit: opts.poolSize ?? 5,
        // 6.4.3: ライブラリが前提とするドライバ設定
        supportBigNumbers: true,
        bigNumberStrings: true,
        timezone: "Z",
      });
      pool.on("connection", (c) => c.query("SET time_zone = '+00:00'"));
      return new Kysely<any>({ dialect: new MysqlDialect({ pool }) });
    };
    const db = await open();
    await runAll(db, [...DDL.mysql, ...extraDdl]);
    return {
      name,
      dialect: mysqlDialect(),
      db,
      open,
      exec: (s) => runAll(db, s),
      tables: TABLES,
      reset: async () => {
        for (const t of FK_TABLES) await sql.raw(`delete from \`${t}\``).execute(db);
        for (const t of TABLES.filter((x) => !FK_TABLES.includes(x))) {
          await sql.raw(`truncate table \`${t}\``).execute(db);
        }
      },
      teardown: async () => {
        await db.destroy();
      },
    };
  }

  const open = async () => {
    const raw = new Database(":memory:");
    raw.defaultSafeIntegers(true);
    raw.pragma("foreign_keys = ON");
    raw.pragma("busy_timeout = 2000");
    return new Kysely<any>({ dialect: new SqliteDialect({ database: raw }) });
  };
  const db = await open();
  await runAll(db, [...DDL.sqlite, ...extraDdl]);
  return {
    name,
    dialect: sqliteDialect(),
    db,
    open,
    exec: (s) => runAll(db, s),
    tables: TABLES,
    reset: async () => {
      for (const t of [...FK_TABLES, ...TABLES.filter((x) => !FK_TABLES.includes(x))]) {
        await sql.raw(`delete from ${t}`).execute(db);
      }
      await sql.raw(`delete from sqlite_sequence`).execute(db);
    },
    teardown: async () => {
      await db.destroy();
    },
  };
}
